//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddToRelayList.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SmtpInventoryIP
    {
        public int InventoryId { get; set; }
        public string IP { get; set; }
    }
}
